# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(891, 357)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(700, 310, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 861, 179))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sec_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_max.setMaximum(60)
        self.sec_max.setProperty("value", 60)
        self.sec_max.setObjectName("sec_max")
        self.gridLayout.addWidget(self.sec_max, 2, 7, 1, 1)
        self.week_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.week_label.setObjectName("week_label")
        self.gridLayout.addWidget(self.week_label, 0, 4, 1, 1)
        self.t_long_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.t_long_label.setObjectName("t_long_label")
        self.gridLayout.addWidget(self.t_long_label, 4, 0, 1, 1)
        self.sec_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_period.setSuffix("")
        self.sec_period.setPrefix("")
        self.sec_period.setMinimum(1)
        self.sec_period.setProperty("value", 60)
        self.sec_period.setObjectName("sec_period")
        self.gridLayout.addWidget(self.sec_period, 3, 7, 1, 1)
        self.period_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.period_label.setObjectName("period_label")
        self.gridLayout.addWidget(self.period_label, 3, 0, 1, 1)
        self.doy_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.doy_label.setObjectName("doy_label")
        self.gridLayout.addWidget(self.doy_label, 0, 8, 1, 1)
        self.minu_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_min.setMaximum(60)
        self.minu_min.setObjectName("minu_min")
        self.gridLayout.addWidget(self.minu_min, 1, 6, 1, 1)
        self.mon_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mon_label.setObjectName("mon_label")
        self.gridLayout.addWidget(self.mon_label, 0, 2, 1, 1)
        self.mon_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_long.setMinimum(0)
        self.mon_long.setMaximum(12)
        self.mon_long.setProperty("value", 0)
        self.mon_long.setObjectName("mon_long")
        self.gridLayout.addWidget(self.mon_long, 4, 2, 1, 1)
        self.hour_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_max.setMaximum(24)
        self.hour_max.setProperty("value", 24)
        self.hour_max.setObjectName("hour_max")
        self.gridLayout.addWidget(self.hour_max, 2, 5, 1, 1)
        self.day_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_long.setMinimum(0)
        self.day_long.setMaximum(31)
        self.day_long.setProperty("value", 0)
        self.day_long.setObjectName("day_long")
        self.gridLayout.addWidget(self.day_long, 4, 3, 1, 1)
        self.year_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_min.setMinimum(1970)
        self.year_min.setMaximum(9999)
        self.year_min.setProperty("value", 2020)
        self.year_min.setObjectName("year_min")
        self.gridLayout.addWidget(self.year_min, 1, 1, 1, 1)
        self.sec_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_min.setObjectName("sec_min")
        self.gridLayout.addWidget(self.sec_min, 1, 7, 1, 1)
        self.week_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.week_min.setMinimum(0)
        self.week_min.setMaximum(7)
        self.week_min.setProperty("value", 0)
        self.week_min.setObjectName("week_min")
        self.gridLayout.addWidget(self.week_min, 1, 4, 1, 1)
        self.day_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_min.setMinimum(1)
        self.day_min.setMaximum(31)
        self.day_min.setObjectName("day_min")
        self.gridLayout.addWidget(self.day_min, 1, 3, 1, 1)
        self.minu_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_period.setMinimum(1)
        self.minu_period.setProperty("value", 60)
        self.minu_period.setObjectName("minu_period")
        self.gridLayout.addWidget(self.minu_period, 3, 6, 1, 1)
        self.mon_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_period.setMinimum(1)
        self.mon_period.setMaximum(12)
        self.mon_period.setObjectName("mon_period")
        self.gridLayout.addWidget(self.mon_period, 3, 2, 1, 1)
        self.mon_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_min.setMinimum(1)
        self.mon_min.setMaximum(12)
        self.mon_min.setObjectName("mon_min")
        self.gridLayout.addWidget(self.mon_min, 1, 2, 1, 1)
        self.day_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_max.setMinimum(1)
        self.day_max.setMaximum(31)
        self.day_max.setProperty("value", 31)
        self.day_max.setObjectName("day_max")
        self.gridLayout.addWidget(self.day_max, 2, 3, 1, 1)
        self.hour_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_period.setMinimum(1)
        self.hour_period.setMaximum(24)
        self.hour_period.setProperty("value", 24)
        self.hour_period.setObjectName("hour_period")
        self.gridLayout.addWidget(self.hour_period, 3, 5, 1, 1)
        self.year_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_long.setMinimum(0)
        self.year_long.setMaximum(9999)
        self.year_long.setProperty("value", 0)
        self.year_long.setObjectName("year_long")
        self.gridLayout.addWidget(self.year_long, 4, 1, 1, 1)
        self.minu_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.minu_label.setObjectName("minu_label")
        self.gridLayout.addWidget(self.minu_label, 0, 6, 1, 1)
        self.minu_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_long.setMinimum(0)
        self.minu_long.setMaximum(9999)
        self.minu_long.setProperty("value", 0)
        self.minu_long.setObjectName("minu_long")
        self.gridLayout.addWidget(self.minu_long, 4, 6, 1, 1)
        self.week_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.week_max.setMinimum(0)
        self.week_max.setMaximum(7)
        self.week_max.setProperty("value", 1)
        self.week_max.setObjectName("week_max")
        self.gridLayout.addWidget(self.week_max, 2, 4, 1, 1)
        self.year_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_max.setMinimum(1970)
        self.year_max.setMaximum(9999)
        self.year_max.setSingleStep(1)
        self.year_max.setProperty("value", 2030)
        self.year_max.setObjectName("year_max")
        self.gridLayout.addWidget(self.year_max, 2, 1, 1, 1)
        self.hour_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_long.setMinimum(0)
        self.hour_long.setMaximum(24)
        self.hour_long.setProperty("value", 1)
        self.hour_long.setObjectName("hour_long")
        self.gridLayout.addWidget(self.hour_long, 4, 5, 1, 1)
        self.hour_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.hour_label.setObjectName("hour_label")
        self.gridLayout.addWidget(self.hour_label, 0, 5, 1, 1)
        self.min_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.min_label.setObjectName("min_label")
        self.gridLayout.addWidget(self.min_label, 1, 0, 1, 1)
        self.hour_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_min.setMaximum(24)
        self.hour_min.setObjectName("hour_min")
        self.gridLayout.addWidget(self.hour_min, 1, 5, 1, 1)
        self.max_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.max_label.setObjectName("max_label")
        self.gridLayout.addWidget(self.max_label, 2, 0, 1, 1)
        self.sec_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_long.setMinimum(0)
        self.sec_long.setMaximum(9999)
        self.sec_long.setProperty("value", 0)
        self.sec_long.setObjectName("sec_long")
        self.gridLayout.addWidget(self.sec_long, 4, 7, 1, 1)
        self.week_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.week_period.setMinimum(1)
        self.week_period.setMaximum(7)
        self.week_period.setObjectName("week_period")
        self.gridLayout.addWidget(self.week_period, 3, 4, 1, 1)
        self.minu_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_max.setMaximum(60)
        self.minu_max.setProperty("value", 60)
        self.minu_max.setObjectName("minu_max")
        self.gridLayout.addWidget(self.minu_max, 2, 6, 1, 1)
        self.year_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_period.setMinimum(1)
        self.year_period.setMaximum(9999)
        self.year_period.setObjectName("year_period")
        self.gridLayout.addWidget(self.year_period, 3, 1, 1, 1)
        self.sec_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sec_label.setObjectName("sec_label")
        self.gridLayout.addWidget(self.sec_label, 0, 7, 1, 1)
        self.day_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_period.setMinimum(1)
        self.day_period.setObjectName("day_period")
        self.gridLayout.addWidget(self.day_period, 3, 3, 1, 1)
        self.day_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.day_label.setObjectName("day_label")
        self.gridLayout.addWidget(self.day_label, 0, 3, 1, 1)
        self.mon_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_max.setMinimum(1)
        self.mon_max.setMaximum(12)
        self.mon_max.setProperty("value", 12)
        self.mon_max.setObjectName("mon_max")
        self.gridLayout.addWidget(self.mon_max, 2, 2, 1, 1)
        self.year_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.year_label.setObjectName("year_label")
        self.gridLayout.addWidget(self.year_label, 0, 1, 1, 1)
        self.sod_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sod_label.setObjectName("sod_label")
        self.gridLayout.addWidget(self.sod_label, 0, 9, 1, 1)
        self.doy_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.doy_period.setMinimum(1)
        self.doy_period.setMaximum(366)
        self.doy_period.setProperty("value", 1)
        self.doy_period.setObjectName("doy_period")
        self.gridLayout.addWidget(self.doy_period, 3, 8, 1, 1)
        self.doy_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.doy_max.setMinimum(1)
        self.doy_max.setMaximum(366)
        self.doy_max.setProperty("value", 1)
        self.doy_max.setObjectName("doy_max")
        self.gridLayout.addWidget(self.doy_max, 2, 8, 1, 1)
        self.doy_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.doy_min.setMinimum(1)
        self.doy_min.setMaximum(366)
        self.doy_min.setProperty("value", 1)
        self.doy_min.setObjectName("doy_min")
        self.gridLayout.addWidget(self.doy_min, 1, 8, 1, 1)
        self.sod_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sod_min.setMinimum(0)
        self.sod_min.setMaximum(86400)
        self.sod_min.setSingleStep(1)
        self.sod_min.setProperty("value", 0)
        self.sod_min.setObjectName("sod_min")
        self.gridLayout.addWidget(self.sod_min, 1, 9, 1, 1)
        self.sod_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sod_max.setMinimum(0)
        self.sod_max.setMaximum(86400)
        self.sod_max.setSingleStep(1)
        self.sod_max.setProperty("value", 0)
        self.sod_max.setObjectName("sod_max")
        self.gridLayout.addWidget(self.sod_max, 2, 9, 1, 1)
        self.sod_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sod_period.setMinimum(0)
        self.sod_period.setMaximum(86400)
        self.sod_period.setSingleStep(1)
        self.sod_period.setProperty("value", 0)
        self.sod_period.setObjectName("sod_period")
        self.gridLayout.addWidget(self.sod_period, 3, 9, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 230, 191, 106))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.recid_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.recid_label.setObjectName("recid_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.recid_label)
        self.typeid_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.typeid_label.setObjectName("typeid_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.typeid_label)
        self.recid_spin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.recid_spin.setMinimum(-1)
        self.recid_spin.setProperty("value", -1)
        self.recid_spin.setObjectName("recid_spin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.recid_spin)
        self.typeid_spin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.typeid_spin.setMinimum(-1)
        self.typeid_spin.setProperty("value", -1)
        self.typeid_spin.setObjectName("typeid_spin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.typeid_spin)
        self.name_comb = QtWidgets.QComboBox(self.formLayoutWidget)
        self.name_comb.setEditable(True)
        self.name_comb.setObjectName("name_comb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_comb)
        self.add_to_db = QtWidgets.QPushButton(Dialog)
        self.add_to_db.setGeometry(QtCore.QRect(790, 270, 81, 30))
        self.add_to_db.setObjectName("add_to_db")
        self.list_out_tasks = QtWidgets.QPushButton(Dialog)
        self.list_out_tasks.setGeometry(QtCore.QRect(790, 230, 81, 30))
        self.list_out_tasks.setObjectName("list_out_tasks")
        self.remove_tasks = QtWidgets.QPushButton(Dialog)
        self.remove_tasks.setGeometry(QtCore.QRect(699, 230, 81, 30))
        self.remove_tasks.setObjectName("remove_tasks")
        self.delete_db = QtWidgets.QPushButton(Dialog)
        self.delete_db.setGeometry(QtCore.QRect(700, 270, 81, 30))
        self.delete_db.setObjectName("delete_db")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.week_label.setText(_translate("Dialog", "星期"))
        self.t_long_label.setText(_translate("Dialog", "时长"))
        self.period_label.setText(_translate("Dialog", "间隔"))
        self.doy_label.setText(_translate("Dialog", "DoY"))
        self.mon_label.setText(_translate("Dialog", "月"))
        self.minu_label.setText(_translate("Dialog", "分"))
        self.hour_label.setText(_translate("Dialog", "时"))
        self.min_label.setText(_translate("Dialog", "最小"))
        self.max_label.setText(_translate("Dialog", "最大"))
        self.sec_label.setText(_translate("Dialog", "秒"))
        self.day_label.setText(_translate("Dialog", "日"))
        self.year_label.setText(_translate("Dialog", "年"))
        self.sod_label.setText(_translate("Dialog", "SoD"))
        self.name_label.setText(_translate("Dialog", "name"))
        self.recid_label.setText(_translate("Dialog", "rec_id"))
        self.typeid_label.setText(_translate("Dialog", "type_id"))
        self.add_to_db.setText(_translate("Dialog", "添加/更新"))
        self.list_out_tasks.setText(_translate("Dialog", "列出任务"))
        self.remove_tasks.setText(_translate("Dialog", "清除任务"))
        self.delete_db.setText(_translate("Dialog", "删除"))
