# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 250)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 210, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 10, 191, 106))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.recid_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.recid_label.setObjectName("recid_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.recid_label)
        self.typeid_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.typeid_label.setObjectName("typeid_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.typeid_label)
        self.recid_spin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.recid_spin.setMinimum(-1)
        self.recid_spin.setProperty("value", -1)
        self.recid_spin.setObjectName("recid_spin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.recid_spin)
        self.typeid_spin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.typeid_spin.setMinimum(-1)
        self.typeid_spin.setProperty("value", -1)
        self.typeid_spin.setObjectName("typeid_spin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.typeid_spin)
        self.name_comb = QtWidgets.QComboBox(self.formLayoutWidget)
        self.name_comb.setEditable(True)
        self.name_comb.setObjectName("name_comb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_comb)
        self.add_to_db = QtWidgets.QPushButton(Dialog)
        self.add_to_db.setGeometry(QtCore.QRect(370, 170, 81, 30))
        self.add_to_db.setObjectName("add_to_db")
        self.list_out_tasks = QtWidgets.QPushButton(Dialog)
        self.list_out_tasks.setGeometry(QtCore.QRect(370, 130, 81, 30))
        self.list_out_tasks.setObjectName("list_out_tasks")
        self.remove_tasks = QtWidgets.QPushButton(Dialog)
        self.remove_tasks.setGeometry(QtCore.QRect(279, 130, 81, 30))
        self.remove_tasks.setObjectName("remove_tasks")
        self.delete_db = QtWidgets.QPushButton(Dialog)
        self.delete_db.setGeometry(QtCore.QRect(280, 170, 81, 30))
        self.delete_db.setObjectName("delete_db")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 234, 142))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.cron_lab = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.cron_lab.setObjectName("cron_lab")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cron_lab)
        self.start_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.start_label.setObjectName("start_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.start_label)
        self.stop_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.stop_label.setObjectName("stop_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stop_label)
        self.time_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.time_label.setObjectName("time_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.time_label)
        self.start = QtWidgets.QDateTimeEdit(self.formLayoutWidget_2)
        self.start.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.start.setObjectName("start")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.start)
        self.stop = QtWidgets.QDateTimeEdit(self.formLayoutWidget_2)
        self.stop.setDateTime(QtCore.QDateTime(QtCore.QDate(2030, 1, 1), QtCore.QTime(0, 0, 0)))
        self.stop.setObjectName("stop")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stop)
        self.cron_text = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.cron_text.setObjectName("cron_text")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cron_text)
        self.long_text = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.long_text.setObjectName("long_text")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.long_text)
        self.preview = QtWidgets.QPushButton(Dialog)
        self.preview.setGeometry(QtCore.QRect(200, 170, 71, 30))
        self.preview.setObjectName("preview")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_label.setText(_translate("Dialog", "name"))
        self.recid_label.setText(_translate("Dialog", "rec_id"))
        self.typeid_label.setText(_translate("Dialog", "type_id"))
        self.add_to_db.setText(_translate("Dialog", "添加/更新"))
        self.list_out_tasks.setText(_translate("Dialog", "列出任务"))
        self.remove_tasks.setText(_translate("Dialog", "清除任务"))
        self.delete_db.setText(_translate("Dialog", "删除"))
        self.cron_lab.setText(_translate("Dialog", "Cron"))
        self.start_label.setText(_translate("Dialog", "开始"))
        self.stop_label.setText(_translate("Dialog", "结束"))
        self.time_label.setText(_translate("Dialog", "时长"))
        self.start.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd hh:mm"))
        self.stop.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd hh:mm"))
        self.cron_text.setText(_translate("Dialog", "0 0 0 * * *"))
        self.long_text.setText(_translate("Dialog", "1:00:00"))
        self.preview.setText(_translate("Dialog", "预览"))
