# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_task_gen.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(891, 357)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(700, 310, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 861, 179))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sec_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_max.setMaximum(60)
        self.sec_max.setProperty("value", 60)
        self.sec_max.setObjectName("sec_max")
        self.gridLayout.addWidget(self.sec_max, 2, 7, 1, 1)
        self.week = QtWidgets.QLabel(self.gridLayoutWidget)
        self.week.setObjectName("week")
        self.gridLayout.addWidget(self.week, 0, 4, 1, 1)
        self.t_long = QtWidgets.QLabel(self.gridLayoutWidget)
        self.t_long.setObjectName("t_long")
        self.gridLayout.addWidget(self.t_long, 4, 0, 1, 1)
        self.sec_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_period.setSuffix("")
        self.sec_period.setPrefix("")
        self.sec_period.setMinimum(1)
        self.sec_period.setObjectName("sec_period")
        self.gridLayout.addWidget(self.sec_period, 3, 7, 1, 1)
        self.period = QtWidgets.QLabel(self.gridLayoutWidget)
        self.period.setObjectName("period")
        self.gridLayout.addWidget(self.period, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 8, 1, 1)
        self.minu_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_min.setMaximum(60)
        self.minu_min.setObjectName("minu_min")
        self.gridLayout.addWidget(self.minu_min, 1, 6, 1, 1)
        self.mon = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mon.setObjectName("mon")
        self.gridLayout.addWidget(self.mon, 0, 2, 1, 1)
        self.mon_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_long.setMinimum(0)
        self.mon_long.setMaximum(12)
        self.mon_long.setProperty("value", 0)
        self.mon_long.setObjectName("mon_long")
        self.gridLayout.addWidget(self.mon_long, 4, 2, 1, 1)
        self.hour_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_max.setMaximum(24)
        self.hour_max.setProperty("value", 24)
        self.hour_max.setObjectName("hour_max")
        self.gridLayout.addWidget(self.hour_max, 2, 5, 1, 1)
        self.day_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_long.setMinimum(0)
        self.day_long.setMaximum(31)
        self.day_long.setProperty("value", 0)
        self.day_long.setObjectName("day_long")
        self.gridLayout.addWidget(self.day_long, 4, 3, 1, 1)
        self.year_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_min.setMinimum(1970)
        self.year_min.setMaximum(9999)
        self.year_min.setProperty("value", 2020)
        self.year_min.setObjectName("year_min")
        self.gridLayout.addWidget(self.year_min, 1, 1, 1, 1)
        self.sec_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_min.setObjectName("sec_min")
        self.gridLayout.addWidget(self.sec_min, 1, 7, 1, 1)
        self.week_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.week_min.setMinimum(1)
        self.week_min.setMaximum(7)
        self.week_min.setObjectName("week_min")
        self.gridLayout.addWidget(self.week_min, 1, 4, 1, 1)
        self.day_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_min.setMinimum(1)
        self.day_min.setMaximum(31)
        self.day_min.setObjectName("day_min")
        self.gridLayout.addWidget(self.day_min, 1, 3, 1, 1)
        self.minu_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_period.setMinimum(1)
        self.minu_period.setObjectName("minu_period")
        self.gridLayout.addWidget(self.minu_period, 3, 6, 1, 1)
        self.mon_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_period.setMinimum(1)
        self.mon_period.setMaximum(12)
        self.mon_period.setObjectName("mon_period")
        self.gridLayout.addWidget(self.mon_period, 3, 2, 1, 1)
        self.mon_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_min.setMinimum(1)
        self.mon_min.setMaximum(12)
        self.mon_min.setObjectName("mon_min")
        self.gridLayout.addWidget(self.mon_min, 1, 2, 1, 1)
        self.day_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_max.setMinimum(1)
        self.day_max.setMaximum(31)
        self.day_max.setProperty("value", 31)
        self.day_max.setObjectName("day_max")
        self.gridLayout.addWidget(self.day_max, 2, 3, 1, 1)
        self.hour_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_period.setMinimum(1)
        self.hour_period.setMaximum(24)
        self.hour_period.setObjectName("hour_period")
        self.gridLayout.addWidget(self.hour_period, 3, 5, 1, 1)
        self.year_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_long.setMinimum(0)
        self.year_long.setMaximum(9999)
        self.year_long.setProperty("value", 0)
        self.year_long.setObjectName("year_long")
        self.gridLayout.addWidget(self.year_long, 4, 1, 1, 1)
        self.minu = QtWidgets.QLabel(self.gridLayoutWidget)
        self.minu.setObjectName("minu")
        self.gridLayout.addWidget(self.minu, 0, 6, 1, 1)
        self.minu_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_long.setMinimum(0)
        self.minu_long.setMaximum(9999)
        self.minu_long.setProperty("value", 0)
        self.minu_long.setObjectName("minu_long")
        self.gridLayout.addWidget(self.minu_long, 4, 6, 1, 1)
        self.week_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.week_max.setMinimum(1)
        self.week_max.setMaximum(7)
        self.week_max.setProperty("value", 7)
        self.week_max.setObjectName("week_max")
        self.gridLayout.addWidget(self.week_max, 2, 4, 1, 1)
        self.year_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_max.setMinimum(1970)
        self.year_max.setMaximum(9999)
        self.year_max.setSingleStep(1)
        self.year_max.setProperty("value", 2100)
        self.year_max.setObjectName("year_max")
        self.gridLayout.addWidget(self.year_max, 2, 1, 1, 1)
        self.hour_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_long.setMinimum(0)
        self.hour_long.setMaximum(24)
        self.hour_long.setProperty("value", 1)
        self.hour_long.setObjectName("hour_long")
        self.gridLayout.addWidget(self.hour_long, 4, 5, 1, 1)
        self.hour = QtWidgets.QLabel(self.gridLayoutWidget)
        self.hour.setObjectName("hour")
        self.gridLayout.addWidget(self.hour, 0, 5, 1, 1)
        self.min = QtWidgets.QLabel(self.gridLayoutWidget)
        self.min.setObjectName("min")
        self.gridLayout.addWidget(self.min, 1, 0, 1, 1)
        self.hour_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hour_min.setMaximum(24)
        self.hour_min.setObjectName("hour_min")
        self.gridLayout.addWidget(self.hour_min, 1, 5, 1, 1)
        self.max = QtWidgets.QLabel(self.gridLayoutWidget)
        self.max.setObjectName("max")
        self.gridLayout.addWidget(self.max, 2, 0, 1, 1)
        self.sec_long = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sec_long.setMinimum(0)
        self.sec_long.setMaximum(9999)
        self.sec_long.setProperty("value", 0)
        self.sec_long.setObjectName("sec_long")
        self.gridLayout.addWidget(self.sec_long, 4, 7, 1, 1)
        self.week_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.week_period.setMinimum(1)
        self.week_period.setObjectName("week_period")
        self.gridLayout.addWidget(self.week_period, 3, 4, 1, 1)
        self.minu_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.minu_max.setMaximum(60)
        self.minu_max.setProperty("value", 60)
        self.minu_max.setObjectName("minu_max")
        self.gridLayout.addWidget(self.minu_max, 2, 6, 1, 1)
        self.year_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.year_period.setMinimum(1)
        self.year_period.setMaximum(9999)
        self.year_period.setObjectName("year_period")
        self.gridLayout.addWidget(self.year_period, 3, 1, 1, 1)
        self.sec = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sec.setObjectName("sec")
        self.gridLayout.addWidget(self.sec, 0, 7, 1, 1)
        self.day_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.day_period.setMinimum(1)
        self.day_period.setObjectName("day_period")
        self.gridLayout.addWidget(self.day_period, 3, 3, 1, 1)
        self.day = QtWidgets.QLabel(self.gridLayoutWidget)
        self.day.setObjectName("day")
        self.gridLayout.addWidget(self.day, 0, 3, 1, 1)
        self.mon_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mon_max.setMinimum(1)
        self.mon_max.setMaximum(12)
        self.mon_max.setProperty("value", 12)
        self.mon_max.setObjectName("mon_max")
        self.gridLayout.addWidget(self.mon_max, 2, 2, 1, 1)
        self.year = QtWidgets.QLabel(self.gridLayoutWidget)
        self.year.setObjectName("year")
        self.gridLayout.addWidget(self.year, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 9, 1, 1)
        self.doy_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.doy_period.setMinimum(1)
        self.doy_period.setMaximum(366)
        self.doy_period.setProperty("value", 1)
        self.doy_period.setObjectName("doy_period")
        self.gridLayout.addWidget(self.doy_period, 3, 8, 1, 1)
        self.doy_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.doy_max.setMinimum(1)
        self.doy_max.setMaximum(366)
        self.doy_max.setProperty("value", 1)
        self.doy_max.setObjectName("doy_max")
        self.gridLayout.addWidget(self.doy_max, 2, 8, 1, 1)
        self.doy_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.doy_min.setMinimum(1)
        self.doy_min.setMaximum(366)
        self.doy_min.setProperty("value", 1)
        self.doy_min.setObjectName("doy_min")
        self.gridLayout.addWidget(self.doy_min, 1, 8, 1, 1)
        self.sod_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sod_min.setMinimum(0)
        self.sod_min.setMaximum(86400)
        self.sod_min.setSingleStep(1)
        self.sod_min.setProperty("value", 0)
        self.sod_min.setObjectName("sod_min")
        self.gridLayout.addWidget(self.sod_min, 1, 9, 1, 1)
        self.sod_max = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sod_max.setMinimum(0)
        self.sod_max.setMaximum(86400)
        self.sod_max.setSingleStep(1)
        self.sod_max.setProperty("value", 0)
        self.sod_max.setObjectName("sod_max")
        self.gridLayout.addWidget(self.sod_max, 2, 9, 1, 1)
        self.sod_period = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sod_period.setMinimum(0)
        self.sod_period.setMaximum(86400)
        self.sod_period.setSingleStep(1)
        self.sod_period.setProperty("value", 0)
        self.sod_period.setObjectName("sod_period")
        self.gridLayout.addWidget(self.sod_period, 3, 9, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 230, 191, 106))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setMinimum(-1)
        self.spinBox.setProperty("value", -1)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_2.setMinimum(-1)
        self.spinBox_2.setProperty("value", -1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.week.setText(_translate("Dialog", "星期"))
        self.t_long.setText(_translate("Dialog", "时长"))
        self.period.setText(_translate("Dialog", "间隔"))
        self.label_4.setText(_translate("Dialog", "DoY"))
        self.mon.setText(_translate("Dialog", "月"))
        self.minu.setText(_translate("Dialog", "分"))
        self.hour.setText(_translate("Dialog", "时"))
        self.min.setText(_translate("Dialog", "最小"))
        self.max.setText(_translate("Dialog", "最大"))
        self.sec.setText(_translate("Dialog", "秒"))
        self.day.setText(_translate("Dialog", "日"))
        self.year.setText(_translate("Dialog", "年"))
        self.label_5.setText(_translate("Dialog", "SoD"))
        self.label.setText(_translate("Dialog", "name"))
        self.label_2.setText(_translate("Dialog", "rec_id"))
        self.label_3.setText(_translate("Dialog", "type_id"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "名称"))
