# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1417, 633)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PlotWidget = PlotWidget(self.centralwidget)
        self.PlotWidget.setGeometry(QtCore.QRect(0, 0, 750, 300))
        self.PlotWidget.setMinimumSize(QtCore.QSize(750, 300))
        self.PlotWidget.setMaximumSize(QtCore.QSize(750, 300))
        self.PlotWidget.setObjectName("PlotWidget")
        self.update_view = QtWidgets.QPushButton(self.centralwidget)
        self.update_view.setGeometry(QtCore.QRect(520, 340, 94, 27))
        self.update_view.setObjectName("update_view")
        self.year = QtWidgets.QSpinBox(self.centralwidget)
        self.year.setGeometry(QtCore.QRect(520, 310, 89, 28))
        self.year.setMaximum(9999)
        self.year.setObjectName("year")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 310, 501, 209))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.is_use_re = QtWidgets.QCheckBox(self.layoutWidget)
        self.is_use_re.setObjectName("is_use_re")
        self.gridLayout.addWidget(self.is_use_re, 4, 3, 1, 1)
        self.min_sta = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.min_sta.setMaximumSize(QtCore.QSize(180, 16777215))
        self.min_sta.setObjectName("min_sta")
        self.gridLayout.addWidget(self.min_sta, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.min_time = QtWidgets.QLineEdit(self.layoutWidget)
        self.min_time.setMaximumSize(QtCore.QSize(200, 16777215))
        self.min_time.setObjectName("min_time")
        self.gridLayout.addWidget(self.min_time, 3, 1, 1, 1)
        self.max_sta = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.max_sta.setMaximumSize(QtCore.QSize(180, 16777215))
        self.max_sta.setObjectName("max_sta")
        self.gridLayout.addWidget(self.max_sta, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.is_include_sub = QtWidgets.QCheckBox(self.layoutWidget)
        self.is_include_sub.setObjectName("is_include_sub")
        self.gridLayout.addWidget(self.is_include_sub, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.max_time = QtWidgets.QLineEdit(self.layoutWidget)
        self.max_time.setMaximumSize(QtCore.QSize(200, 16777215))
        self.max_time.setObjectName("max_time")
        self.gridLayout.addWidget(self.max_time, 3, 2, 1, 1)
        self.name2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.name2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.name2.setObjectName("name2")
        self.gridLayout.addWidget(self.name2, 4, 2, 1, 1)
        self.min_end = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.min_end.setMaximumSize(QtCore.QSize(180, 16777215))
        self.min_end.setObjectName("min_end")
        self.gridLayout.addWidget(self.min_end, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.name1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.name1.setObjectName("name1")
        self.gridLayout.addWidget(self.name1, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 5, 1, 1, 1)
        self.max_end = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.max_end.setMaximumSize(QtCore.QSize(180, 16777215))
        self.max_end.setObjectName("max_end")
        self.gridLayout.addWidget(self.max_end, 2, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(755, 1, 661, 581))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1417, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.update_view.setText(_translate("MainWindow", "更新"))
        self.label_2.setText(_translate("MainWindow", "开始"))
        self.is_use_re.setText(_translate("MainWindow", "正则"))
        self.min_sta.setDisplayFormat(_translate("MainWindow", "yyyy/M/d hh:mm"))
        self.label_7.setText(_translate("MainWindow", "状态"))
        self.max_sta.setDisplayFormat(_translate("MainWindow", "yyyy/M/d hh:mm"))
        self.label_5.setText(_translate("MainWindow", "最大"))
        self.is_include_sub.setText(_translate("MainWindow", "含子任务"))
        self.label_3.setText(_translate("MainWindow", "结束"))
        self.min_end.setDisplayFormat(_translate("MainWindow", "yyyy/M/d hh:mm"))
        self.label.setText(_translate("MainWindow", "名称"))
        self.label_6.setText(_translate("MainWindow", "时长"))
        self.label_4.setText(_translate("MainWindow", "最小"))
        self.max_end.setDisplayFormat(_translate("MainWindow", "yyyy/M/d hh:mm"))
from pyqtgraph import PlotWidget
